services:
  mongo:
    container_name: tagflow-db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${DATABASE_PORT}/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    image: mongo:latest
    restart: always
    ports:
      - 27017:${DATABASE_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - tagflow-net
  
  mongo-express:
    container_name: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express:latest
    profiles: [ 'dev' ]
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongo:${DATABASE_PORT}/
      ME_CONFIG_BASICAUTH: false
    networks:
      - tagflow-net
  
  api:
    depends_on:
      mongo:
        condition: service_healthy
    container_name: tagflow
    image: jpth/tagflow
    profiles: [ 'prod' ]
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/tagflow
    networks:
      - tagflow-net
    
volumes:
  mongo-data:

networks:
  tagflow-net:
    driver: bridge